name: Deploy Laravel Project on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
      # Commit mesajında [build] ifadesi varsa True olur.
    env:
      SHOULD_BUILD: ${{ contains(github.event.head_commit.message, '[build]') }}
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup PHP and Node.js (If Build Required)
        if: env.SHOULD_BUILD == 'true'
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_mysql, bcmath, zip
          tools: composer

      - name: Install Composer & NPM Dependencies
        if: env.SHOULD_BUILD == 'true'
        run: |
          npm install
          composer install --no-scripts

      - name: Build Frontend Assets
        if: env.SHOULD_BUILD == 'true'
        run: npm run build

      - name: Compress Build Files to ZIP
        if: env.SHOULD_BUILD == 'true'
        run: |
          # SADECE vendor, node_modules ve public klasörlerini sıkıştırır
          zip -r deployment_assets.zip vendor node_modules public 
          
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /main.panel/
          exclude: | 
            **/.git* 
            **/.git*/** 
            **/node_modules/** 
            **/vendor/** 
            **/public/backend/**
            **/public/build/**
            **/public/cache/**
            **/public/frontend/**
            **/public/lider_bursa/**
            **/public/resimler/**
            **/public/sitemaps/**
            **/public/uploads/**
            **/public/v1_public/**
            **/public/v2_public/**
            **/public/v3_public/**
            **/public/vendor/**
            **/tests/** 
            **/phpunit.xml 
            **/.env.example 
            **/deploy.yml 
            **/*.md 
            **/.github/**

      - name: Trigger Server Build Commands (Vendor/Node)
        if: env.SHOULD_BUILD == 'true'
        run: |
          echo "Triggering server build for vendor/node_modules creation..."
          # Bu URL'i runBuild metodunu çağıran route ile güncelleyin!
          curl -X GET "https://main.panel.medyayazilimlari.com/deploy"
          